development:
  adapter: postgresql
  encoding: unicode
  database: simple_imbd_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: simple_imbd_test
  pool: 5
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: simple_imbd_production
  pool: 5
  username: postgres
  password: